apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args: ["--dockerfile=Dockerfile",
            "--context=gs://BUCKETNAME",
            "--destination=nexus-direct-docker-private:8083/kubepetclinic:1",
            --insecure-skip-tls-verify]
    volumeMounts:
      - name: kaniko-secret
        mountPath: /root/.docker/
    env:
      - name: NEXUS_APPLICATION_CREDENTIALS
        value: /root/.docker/config.json
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: kaniko-secret
