apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args: ["--dockerfile=Dockerfile",
            "--context=gs://BUCKETNAME",
            "--destination=nexus-direct-docker-private:8083/kubepetclinic:1",
            --insecure-skip-tls-verify]
    volumeMounts:
      - name: docker-config
        mountPath: /root/.docker/
  restartPolicy: Never
  volumes:
    - name: docker-config
      configMap:
        name: docker-config
