apiVersion: v1
kind: Pod
metadata:
  name: kaniko-APPNAME
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args: ["--dockerfile=Dockerfile",
            "--context=gs://BUCKETNAME",
            "--destination=nexus-direct:8083/APPNAME:TAG",
            --insecure-skip-tls-verify] #to make kaniko able to use non ssl repository
    volumeMounts:
      - name: docker-config
        mountPath: /root/.docker/
  restartPolicy: Never
  volumes:
    - name: docker-config
      configMap:
        name: docker-config
