podTemplate(label: 'NVDUpdatePOD', containers: [
        containerTemplate(name: 'maven', image: 'maven:alpine', ttyEnabled: true, command: 'cat')
], volumes: [
        persistentVolumeClaim(mountPath: '/root/.m2/repository', claimName: 'maven-repo', readOnly: false),
        persistentVolumeClaim(mountPath: '/root/NVD', claimName: 'nvd', readOnly: false)
]) {

    node('NVDUpdatePOD') {
        try {
            DriverLoader.load("org.h2.Driver");
            container('maven') {
                dependencyCheckUpdateOnly '/root/NVD'
            }
        } catch (all) {
            //
        }
    }


}

