#!/usr/bin/env python

# import the package
from defectdojo_api import defectdojo
from datetime import datetime, timedelta

def get_productid_by_name(dd, name):

    #List Products
    products = dd.list_products(name)

    if products.success:
        #print(products.data_json(pretty=True))  # Decoded JSON object

        for product in products.data["objects"]:
            if product['name'] == name:
                print "Product " + name + " found in DefectDojo with Id : " + str(product['id'])
                return str(product['id'])
                #print(product['name'] + " " + str(product['id']))  # Print the name of each product
    else:
        print products.message


def create_product(dd, name, product_type):
    dd.create_product(name, "Product automatically generated by CI/CD", product_type)


def get_or_create_product(dd, productName):

    productid = get_productid_by_name(dd, productName)
    if productid == None :
        create_product(dd, productName, 1)
        productid = get_productid_by_name(dd, productName)

    return productid


# setup DefectDojo connection information
host = 'http://localhost:8000'
api_key = 'bdb96e00f8331b6b4d414e3d4f8c824d85b74b0b'
user = 'admin'

# instantiate the DefectDojo api wrapper
dd = defectdojo.DefectDojoAPI(host, api_key, user, 'v1', False, debug=False)


get_or_create_product(dd, "blablablablabla")



