kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: appName-frontend-deployment
spec:
  replicas:
  template:
    metadata:
      name: frontend
      labels:
        app: appName
        role: frontend
        env: production
    spec:
      containers:
      - name: frontend
        image: NODEIP:30083/CONTAINERNAME
#        resources:
#          limits:
#            memory: "500Mi"
#            cpu: "100m"
        imagePullPolicy: Always
#        readinessProbe:
#          httpGet:
#            path: /healthz
#            port: 80
#        command: ["sh", "-c", "app -frontend=true -backend-service=http://gceme-backend:8080 -port=80"]
        ports:
        - name: frontend
          containerPort: 8080
