kind: Service
apiVersion: v1
metadata:
  name: appName-frontend
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: appName
    role: frontend
